default_context:
  name: "deeply"
  version: "0.1.0"
  slug: "deeply"
  command: "deeply"
  cli: "argparse"
  config: "y"
  compat: "custom"
  jupyter: "y"
  sqlite: "y"
  pypy: "y"
  travis: "n"
  appveyor: "n"
  description: "A Deep Learning library"
  author: "Achilles Rasquinha"
  email: "achillesrasquinha@gmail.com"
  keywords: "deep learning"
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: "achillesrasquinha"
  repo_service_reponame: "deeply"
  docker_service_username: "achillesrasquinha"
  docker_service_reponame: "deeply"
  github_action: "y"
  ml: "n"
  editor: "vscode"
  url: "https://github.com/achillesrasquinha/deeply"