default_context:
  name: "deeply"
  version: "0.1.0"
  slug: "deeply"
  command: "deeply"
  cli: "argparse"
  config: "y"
<<<<<<< HEAD
  compat: "custom"
  jupyter: "y"
  sqlite: "y"
  pypy: "y"
  travis: "n"
  appveyor: "n"
  description: "A Deep Learning library"
  author: "Achilles Rasquinha"
  email: "achillesrasquinha@gmail.com"
  keywords: "deep learning"
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: "achillesrasquinha"
  repo_service_reponame: "deeply"
  docker_service_username: "achillesrasquinha"
=======
  compat: "bpyutils"
  jupyter: "n"
  sqlite: "n"
  pypy: "y"
  description: ""
  author: ""
  email: ""
  keywords: ""
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: ""
  repo_service_reponame: "deeply"
  docker_service_username: ""
>>>>>>> template/master
  docker_service_reponame: "deeply"
  github_action: "n"
  ml: "n"
  editor: "vscode"
<<<<<<< HEAD
  url: "https://github.com/achillesrasquinha/deeply"
=======
  url: "https://github.com//deeply"
>>>>>>> template/master
