name: Template

on:
  push:
  
jobs:
  template:
    name: Template
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - uses: achillesrasquinha/boilpy-action
=======
      - uses: achillesrasquinha/boilpy-action@develop
>>>>>>> template/master
      - name: Updating template
        run: |
          echo "Updating template..."